import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxWrapper from "../provider/ReduxWrapper";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body className= 'container'>{children}</body>
      </html>
    </ReduxWrapper>
  );
}
